spring:
  application:
    name: lpzipo-center
  profiles:
    active: dev

---
spring:
  profiles: dev
server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
#    hostname: eureka-server-peer1 #主机名称
  client:
    registerWithEureka: false #由于该应用为注册中心，所以设置为false 代表不向注册中心注册自己
    fetchRegistry: false #由于注册中心的职责就是维护服务实例，并不需要去检索服务，所以也设置为false
#    serviceUrl:
#          defaultZone: http://127.0.0.1:8762/eureka/    #用于高可用  注册中心互相注册